sudo: required
dist: trusty

language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
    packages:
      - gcc-5
      - g++-5
      - clang-3.7

before_install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 50
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 50
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 50
  - if [ ${CC} == "clang" ]; then
    export CC=/usr/bin/clang-3.7 CXX=/usr/bin/clang++-3.7;
    fi

compiler:
  - gcc
  - clang

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - test/crole-test
