version: 0.1.{build}

branches:
  except:
    - gh-pages

skip_tags: true

os: Visual Studio 2015

clone_folder: C:\projects\crole

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release
  
init:
  - git config --global core.autocrlf input
  - cmd: cmake --version
  - cmd: msbuild /version
  
before_build:
  - cd C:\projects\crole
  - mkdir build
  - cd build
  - if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 14 2015
  - if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 14 2015 Win64
  - cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration%

build:
  project: C:\projects\crole\build\crole.sln
  parallel: true
  verbosity: quiet

test_script:
  - C:\projects\crole\build\test\crole-test.exe